---
title: "Figure3_Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Figure3_Analysis"
author: "Sarah Tennant"
date: "18/11/2020"
output: html_document
---



## Run mixed effect model which examines contribution of speed, acceleration and position on firing rate

1. Functions to perform linear mixed effect model
```{r}
source("Functions_Outbound_LMER.R")

```

```{r}

tval_pos_b <- function(df){
  if(length(df) == 1) 
    return(NA) 
  df <- tibble(Rates = as.numeric(Re(df[[1]])), Position = as.numeric(Re(df[[2]])), Acceleration = as.numeric(Re(df[[3]])), Speed = as.numeric(Re(df[[4]])), Trials = as.factor(Re(df[[5]])), Types = as.factor(Re(df[[6]])))
  df <- df %>% 
    subset(Position >= 30 & Position <= 90 & Speed > 3 & Types == 0)
  if(length(df) == 1 | nrow(df) < 3) 
    return(NA) 
  df_int <- lme4::lmer(Rates ~ Position + Speed + Acceleration + (1|Trials), data = df, na.action=na.exclude, REML=FALSE)
  print(coef(summary(df_int))["Position","t value"])
  #print(summary(df_int)[,"t value"])
  prtAnova <- car::Anova(df_int) 
  return(prtAnova$"Pr(>Chisq)"[1])
}
```


2. Run on all cells 
```{r}
spatial_firing <- spatial_firing  %>%
  mutate(o_pos_b = map(spikes_in_time, car_pos_b)) %>%
  mutate(o_speed_b = map(spikes_in_time, car_speed_b)) %>%
  mutate(o_accel_b = map(spikes_in_time, car_accel_b)) %>%
  mutate(o_pos_nb = map(spikes_in_time, car_pos_nb)) %>%
  mutate(o_speed_nb = map(spikes_in_time, car_speed_nb)) %>%
  mutate(o_accel_nb = map(spikes_in_time, car_accel_nb)) %>%
  mutate(o_pos_p = map(spikes_in_time, car_pos_p)) %>%
  mutate(o_speed_p = map(spikes_in_time, car_speed_p)) %>%
  mutate(o_accel_p = map(spikes_in_time, car_accel_p))
```


### ----------------------------------------------------------------------------------------- ###


## Select best model 

1. Write function to perform model selection
```{r}

model_comparison <- function(null_pos, null_speed, null_accel){
  pval <- 0.01
  if( is.na(null_pos) & is.na(null_accel)) {
    return( "None" )
  
  } else if( null_pos < pval & null_accel > pval & null_speed > pval) {
    return( "P" )
    
  } else if( null_pos > pval & null_accel > pval & null_speed < pval) {
    return( "S" ) 
    
  } else if( null_pos > pval & null_accel < pval & null_speed > pval) {
    return( "A" )
    
  } else if( null_pos < pval & null_accel > pval & null_speed < pval) {
    return("PS")
    
  } else if( null_pos < pval & null_accel < pval & null_speed > pval) {
    return( "PA" )
        
  } else if( null_pos > pval & null_accel < pval & null_speed < pval) {
    return("SA")

  } else if( null_pos < pval & null_accel < pval & null_speed < pval) {
    return("PSA")
    
  } else {
    return("None")
  }
}

```

2. Run on all cells in dataframe
```{r}
spatial_firing <- spatial_firing  %>%
    mutate(final_model_o_b  = pmap(list(o_pos_b, o_speed_b, o_accel_b), model_comparison)) %>%
    mutate(final_model_o_nb  = pmap(list(o_pos_nb, o_speed_nb, o_accel_nb), model_comparison))  %>%
    mutate(final_model_o_p  = pmap(list(o_pos_p, o_speed_p, o_accel_p), model_comparison))

```

