---
title: "SetUp"
author: "Matt"
date: "17/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Modified from 'Prelim_Analysis_rewarded' written by Sarah Tennant. Goal here is to load data, functions and required packages. 

```{r}
# Load packages
library(tidyverse)
library(broom)
library(lme4)
library(ggExtra)
library(ggthemes)
library(scales)
library(Hmisc)
library(Metrics)
library(plotrix)
library(pheatmap) # this package lets you make nice heatmaps
library(RColorBrewer) # import color palettes
library(networkD3) # This package lets you make and plot Sankey diagrams
library(zoo) # some mathematical functions that are useful
library(tibbletime)
library(agricolae) # post hoc Tukey test
library(ggallin) # this is for the pseudolog10_trans function used in coeff plots in Figure2_Analysis

# Import functions
source("Functions.R") ## is this even used??? I dont think so! Keeping it just incase..

# Parameter to save figures. Set to 1 if you'd like to save them.
save_figures = 1

# Parameter to save data snapshots as analysis proceeds. Set to 1 to save.
save_results = 0


# Load data
# Alternative file names commented out
#spatial_firing <- readRDS(file="PythonOutput_Concat.Rda")
spatial_firing <- readRDS(file="SpatialFiring_with_1000_shuffles_of.Rda") 
shuffles <- select(spatial_firing_shuffles,c('session_id', 'cluster_id', 'shuffle_results_nb_o', 'shuffle_results_b_o', 'shuffle_results_p_o'))
saveRDS(shuffles, "SpatialFiring_JUST1000_shuffles_final_of.Rda")
spatial_firing <- readRDS(file="PythonOutput_Concat_final_of_withshuffles.Rda") 
# To work on  a subset of data for testing
# spatial_firing <-  slice_head(spatial_firing, n = 10)
```



***Warning***
Spatial firing is a very large object. Even running str takes many minutes.
Look at how we can fix this?

This code chunk can be used to find out about spatial firing
```{r}
options(max.print = 1000)
dim(spatial_firing)
# Things measured:
colnames(spatial_firing)
# Cells:
# row.names(spatial_firing)
# stop from printing too much if looking at variables


options(max.print = 10)
```


