

This scripts aggregate the mixed effect models


### Import


```{r, message=FALSE, include=FALSE}
library(rstatix)
library(feather)
library(tidyverse)
library(rjson)
library(lme4)
library(reticulate)
library(ggeffects)
library(broom)
library(glue)
library(progress)
library(lobstr)

use_condaenv("glm_mec_model")
pd <- import("pandas")

knitr::opts_chunk$set(
  fig.show = "hold"
)

```

### Get all data folder

```{r}
fileList <- Sys.glob("/mnt/datastore/Teris/CurrentBiology_2022/*_mixed_effect_models.pkl")

```


### Read data

```{r}
data <- c()

pbar <- progress_bar$new(total=length(fileList))

tlist = vector(mode = "list", length = length(fileList))
idx = 1

for(f in fileList){
  pbar$tick()
  
  print(glue("Processing {f}...\n"))

  lme_data <- readRDS(f)

  lme_data2 <- lme_data %>% select(-models.fitted_models,
                                    -models.pos_model,
                                    -models.time_model) 
  
  tlist[[idx]] <- lme_data2
  idx = idx + 1
  gc() #need to force gc for large data
    
  
}

data <- bind_rows(tlist)

```


### Merge with lm results

```{r}
lm_results <- read_tsv("/mnt/datastore/Teris/CurrentBiology_2022/all_results_coefficients.csv")

data_merged <- data %>%
  inner_join(lm_results, by=c("session_id"="session_id","cluster_id"="cluster_id")) #need to use named list

data_merged_small <- data_merged[1:20,]
data_merged_small

```


```{r}
saveRDS(data_merged,'/mnt/datastore/Teris/CurrentBiology_2022/all_lme.rds', compress = FALSE) #load previous data
```

