---
title: "R Notebook"
output:
  html_notebook:
    df_print: paged
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
    df_print: paged
---

This scripts aggregate the mixed effect models


### Import


```{r include=FALSE, message=FALSE}
library(rstatix)
library(feather)
library(tidyverse)
library(rjson)
library(lme4)
library(reticulate)
library(ggeffects)
library(broom)
library(glue)
library(progress)
library(ggforce)
library(patchwork)
library(ggpubr)

# knitr::opts_chunk$set(
#   fig.show = "hold",
#   fig.width = 7,
#   fig.asp = 0.6
# )

```

### Load data

```{r}

# Load a particular cohort
use_condaenv("glm_mec_model")
pd <- import("pandas")
pickle <-import("pickle")
cohort = 3 # 2,3,4,5,7
file <- glue("/mnt/datastore/Teris/CurrentBiology_2022/cohort", cohort, "_df4r.pkl")
df <- pd$read_pickle(file)
df <- as_tibble(df)
df_ramp = as_tibble(pd$read_pickle("/mnt/datastore/Teris/CurrentBiology_2022/all_rampscore.pkl"))


```

```{r}

getFiringRate <- function(spiketrain){
  spiketrain[[1]]/100
}

lm_cls <- read_tsv('/mnt/datastore/Teris/CurrentBiology_2022/all_results_coefficients.csv')
df_merged <- df %>% inner_join(lm_cls,by=c("session_id"="session_id","cluster_id"="cluster_id")) %>%
              inner_join(df_ramp, by=c("session_id"="session_id","cluster_id"="cluster_id")) %>%
      filter(ramp_region=="outbound", trial_type=="beaconed") 

# Extract the firing rate
df_merged <- df_merged %>%
  mutate(firingRate = map_dbl(spiketrain, getFiringRate)) 

included_sessions = unique(df$session_id)
df_merged

```

```{r} 
# Find sessions that has a large number of trials to plot
df_num_trials <- df_merged %>% group_by(session_id)  %>% 
  summarise(number_trials=n_distinct(trial_number), first_cluster=first(cluster_id))  %>%
  arrange(desc(number_trials))
df_num_trials

```
Sort the ramp score for easily identification later

```{r}

df_cell <- df_ramp %>% inner_join(lm_cls, by=c("session_id"="session_id","cluster_id"="cluster_id"))
df_pos <- df_cell %>%
  filter(ramp_region=="outbound", trial_type=="beaconed") %>%
  filter(lm_group_b=="Positive") %>%
  filter(session_id %in% included_sessions) %>%
  arrange(desc(score))

df_neg <- df_cell %>%
  filter(ramp_region=="outbound", trial_type=="beaconed") %>%
  filter(final_model_o_b=="P") %>%
  filter(lm_group_b=="Negative") %>%
  filter(session_id %in% included_sessions) %>%
  arrange(score)


df_neg
```

```{r}

 x<- df %>% filter(session_id ==df_pos$session_id[[1]])
n_distinct(x$trial_number)
```


```{r}

# Select a particular recording

# Calculate the trial length 

getTrialLength <-function(data){
  nrow(data)
}


getCell2plot <- function(sessionID, clusterID){
 df_merged %>% filter(session_id==sessionID & cluster_id==clusterID) %>%
    mutate(trial_length_type = recode(trial_length_type, `0` = "Short", `1` = "Middle", `2` = "Long")) %>%
    group_by(cluster_id, trial_length_type, trial_number) %>%
    nest() %>%
    mutate(trial_length = map_int(data, getTrialLength)) %>%
    unnest(data)
    
}


```


#Plot trial time and firing-rate-time plot for a particular session


### Figure S5A
Histogram and firing rate over time

```{r fig.width=3, fig.asp=1}

# Note: the time analysis only includes the rewarded trials, so the actual trial count is much less than the total number of trials

plot_trial_time <- function(df2plot) {
  # plot histogram
df2plot %>%
  filter(cluster_id == df2plot$cluster_id[[1]]) %>% # avoid duplicating data
    group_by(trial_number) %>% 
    summarize(trial_length=first(trial_length)) %>%
    # filter(trial_length<50) %>% # omit trial that is taking too long, e.g. when the animal stops
  ggplot(aes(x=trial_length)) +
    geom_histogram(binwidth = 2 ) +
    labs(x='Time to reward (s)') +
    theme_minimal(base_size=16) +
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
          axis.line = element_line(),text=element_text(size=20))


}

options(repr.plot.width=3, repr.plot.height=3)

df2plot <- getCell2plot(df_num_trials$session_id[[1]], df_num_trials$first_cluster[[1]])

plot_trial_time(df2plot)
ggsave('paper_figures/timeAnalysis_A.pdf',width=4,height=4)

```


Figure S5B

```{r fig.height=4}
plot_fr_vs_time <- function(df2plot){

  df2plot %>% filter(trial_length_type != 'Middle') %>%
    filter(quantile(.$trial_length,0.90)>trial_length) %>% #remove outlier trial that is very long
  ggplot +
    geom_smooth(aes(x=time_relative_outbound, y=firingRate,color=trial_length_type), formula= y ~ x, method = "loess") +
    labs(x='Time from start of track (s)',y='Firing Rate(Hz)',color='Trial length') +
    theme_minimal(base_size=18)+
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
          axis.line = element_line(), text=element_text(size=20))


}

plot_fr_vs_pos <- function(df2plot){

  df2plot %>% filter(trial_length_type != 'Middle') %>%
  filter(quantile(.$trial_length,0.90)>trial_length) %>%
  ggplot +
    geom_smooth(aes(x=position_relative_outbound, y=firingRate,color=trial_length_type), formula= y ~ x,  method = "loess") +
    labs(x='Position from start of track (cm)',y='Firing Rate(Hz)',color='Trial length') +
    theme_minimal(base_size=18)+
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
          axis.line = element_line(), text=element_text(size=20))


}


# options(repr.plot.width=1, repr.plot.height=2)

select_cell <- 12
df2plot <- getCell2plot(df_pos$session_id[[select_cell]], df_pos$cluster_id[[select_cell]])
p1 <- plot_fr_vs_time(df2plot)


p2 <- plot_fr_vs_pos(df2plot)

p1/p2

ggsave('paper_figures/S5B_1.pdf',width=7,height=8)

```
Negative ramp cell

```{r echo=FALSE, message=FALSE, warning=FALSE}
select_cell <- 8 #14,15
df2plot <- getCell2plot(df_neg$session_id[[select_cell]], df_neg$cluster_id[[select_cell]])
p1 <- plot_fr_vs_time(df2plot)
p2 <- plot_fr_vs_pos(df2plot)

p1/p2

ggsave('paper_figures/S5B_2.pdf',width=7,height=8)
```


